set---
title: "Notes w1 R Programming Course"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# R Programming Course, week 1

### R objects
#### Basic object = vector
* vectors can only contain objects of the same class
* except lists, which can contain several classes
* empty vectors can be created with vector()
* inf = infinity, can be used in regular calculations
* L specifies that the vector should be an integer
* NAN = undefined value

#### Atomic objects = 
* characters
* numeric (real numbers)
* integer
* logical (true, false)

#### Attributes
* names/dimnames (dimensionnames)
* dimensions (e.g matrices, arrays)
* classes
* length
* other userdefined metadata
* attributes can be accessed with attributes()



### Determine class of vector x
x <- 4L #### L creates a integer vector
class(x)

> x <- c(4, "a", TRUE)
> class(x)

### rbind function
x <- c(1,3, 5)
y <- c(3, 2, 10)
rbind(x, y)

### Find and print the first position in a list
x <- list(2, "a", "b", TRUE)
x[[1]]

### Simple addation of array vectors
x <- 1:4
y <- 2:3
x + y
or
z <- x + y

### Find and print vectors, from an array vector, that is higher than 10 and assigne them value = 4
x <- c(17, 14, 4, 5, 13, 12, 10)
x[x > 10] <- 4
or
x[x >= 11] <- 4

### Reading tabular data
setwd("/Users/oddbruun/datasciencecoursera/")
read.csv("hw1_data.csv" , sep=";")




### Read only the first few rows of data from a large dataset
sampleData <- read.table("hw1_data.csv", header = TRUE, sep= ",", nrows = 5)

#### Find and set classes of each column
classes <- sapply(sampleData, class)
largeData <- read.table("hw1_data.csv", header = TRUE, sep = ",", colClasses = classes)

#### Look at sampleData
str(largeData)

#### Import the rest of the file
read.csv("hw1_data.csv")

#### View all data in table
View(largeData)



#### Calculate needed memory for importing data table
* rows*columns*8 bytes (for numeric vectors)
* bytes/2^20
* MB to GB



### Find header names
names(data)

### Find total number of rows in dataset
nrow(data) 

### Read the 2 first rows with data
data <- read.csv("hw1_data.csv")
head(data, 2)

### Read the 2 last rows with data
tail(data, 2)

### Find and print data in Ozone column on row 47
data$Ozone[47]
or 
data[47,1]

### Find number of missing values in Ozone column
sum(is.na(data[,1])) 

or

missingNA <- is.na(data$Ozone)
sum(missingNA)

### Find mean of Ozone column excluding missing values
mean(na.omit(data[,1]))

or

Ozone <- na.omit(data$Ozone)
as.numeric(Ozone)
mean(Ozone)

or

ozone <- subset(data, !is.na(Ozone), select = Ozone)
apply(ozone, 2, mean) 




### Extract the subset of rows of the data frame where Ozone values are above 31 and Temp values are above 90. What is the mean of Solar.R in this subset?
data.subO <- data[data$Ozone > 31, , drop = FALSE]
data.subTO <- data.subO[data.subO$Temp > 90, , drop = FALSE]
data.subTOO <- na.omit(data.subTO)
mean(data.subTOO$Solar.R)

or

solar <- subset(data, Temp>90 & Ozone>31, select=Solar.R)
apply(solar, 2, mean) ##### For a data.frame, a margin of 2 indicates columns

### Find the mean of "Temp" when "Month" is equal to 6
dateJune <- data[data$Month == 6, , drop = FALSE]
mean(dateJune$Temp)

or

temp <- subset(data, Month==6, select=Temp)
apply(temp, 2, mean)

### Find the maximum ozone value in the month of May (i.e. Month = 5)
dateMay <- data[data$Month == 5, , drop = FALSE]
dateMay0 <- na.omit(dateMay)
max(dateMay0$Ozone)

or

ozone2 <- subset(data, Month==5 & !is.na(Ozone), select=Ozone)
apply(ozone2, 2, max)






### Notes R programming: week 1

#### Create a frequency table with Factors
x <- factor(c("yes", "no", "yes", "no", "no", "no"))
table(x)  

#### See how factors are represented in R. Stripping the class and left with integers
unclass(x)

### is.na() Used to test objects if they're NA
### is.nan() Used to test if they're NaN
x <- c(1,2,3,NA,10)
is.na(x)
is.nan(x)

y <- c(1,2,3,NaN,10)
is.na(y)

### Create a dataframe
z <- data.frame(Dog=c(1,2,3,4), Cat=c("a", "b", "c", "d"))
z

#### Count rows and columns
nrow(z)
ncol(z)


### Create a matrix and attribute names to rows and columns
names(x) <- c("a", "b", "c")
m <- matrix(1:4, nrow=2, ncol=2, byrow=TRUE)
dimnames(m) <- list(c("a", "b"), c("c", "d"))
m




### Subsetting
#### [always returns an object of the same class as the original]
#### [[used to extract elements of a list of data.frame;  it can only be used to extract a single element and the class of the returned object will not necessarily be a list or data.frame]]
#### $ used to extract element from list or data.frame by name
x <- c("a", "b", "c", "c", "d", "a")

##### Return one vector based on placement
x[1]

##### Return range of vectors based on placement
x[1:4]

##### Return a character vector
x[x > "a"]

##### Return a logical vector
u <- x > "a"
u




### Lists
x <- list(dog=c(1,2,3,4), cat=3.14, squirrel="Hello") ##### Returns the whole list

x[[1]] ##### Return first vector

x[c(1,3)] ##### Return vectors based on location in list

x[[c(1,3)]] ##### Return a single element in first vector in list

x$dog ##### Return values in vector based on name




### Matrices
x <- matrix(1:6, 2, 3) ##### Create matrix with data 1:6, 2 rows and 3 columns

x[,2] ##### Returns second column

x[1,] ##### Returns first row

x[1,2, drop=FALSE] ##### By default, when a single element is retrieved from a matrix, it is returned as a vector of length 1 rather than a 1x1 matrix. This can be turned off with drop=

### Removing NA
z <- c(1, 2, NA, 3, NA, 4)
bad <- is.na(z)
z[!bad]

##### Show which values is missing
w <- c("a", "b", NA, "c", NA, "d")
good <- complete.cases(z,w)
good

##### Prints out only TRUE values
z[good]
w[good]




### Vectorized matrix operations
##### Create two matrixes where x contains numbers from 1:4, and y contains only number 10. Both matrixes should have 2 rows and 2 columns
x <- matrix(1:4,2,2); y<-matrix(rep(10,4),2,2)
##### Prints both matrixes
x; y

##### Multiply all vectors in x with vectors in y
x*y

##### True matrix multiplication; (x row1,1 * y column1,1) + (x row1,2 * y column1,2) = result row1,1   
x %*% y



### Textual formats
#### dput() can be used to reconstruct an R object, after outputting it from R
#### dump() same as dput, but can be used on multiple objects
#### functions for reading data that has been dumped or dputted are source() and dget()

* useful format to store data and read data
* in case of corruption textual formats can be recoverable, beacuse they are edit-able
* preserves metadata
* work better with version controle programs like git, because it can track changes
* not very space efficient




### Reading data from external sources
#### file() open up a connection to an external source, like a file
#### gzfile and bzfile connects to compressed files
#### url connects to a webpage

con <- gzfile("example.gz")
x <- readlines(con, 10) ##### reads the first 10 lines in a file
x

##### writelines() takes a character vector and writes each element one line at a time to the text file

con <- url("www.vg.no", "r")
x <- readlines(con)
head(x) ##### read lines from a webpage






















